export const serviceConstants = {
    FETCH_SITTERS_SUCCESS: 'FETCH_SITTERS_SUCCESS',
    FETCH_SITTERS_FAILURE: 'FETCH_SITTERS_FAILURE',

    FETCH_SITTERS_BYSTRING_SUCCESS: 'FETCH_SITTERS_BYSTRING_SUCCESS',
    FETCH_SITTERS_BYSTRING_FAILURE: 'FETCH_SITTERS_BYSTRING_FAILURE',

    FETCH_JOB_LISTINGS_SUCCESS: 'FETCH_JOB_LISTINGS_SUCCESS',
    FETCH_JOB_LISTINGS_FAILURE: 'FETCH_JOB_LISTINGS_FAILURE',

    ADD_JOB_LISTINGS_SUCCESS : 'ADD_JOB_LISTINGS_SUCCESS',
    ADD_JOB_LISTINGS_FAILURE : 'ADD_JOB_LISTINGS_FAILURE',

    REQUEST_JOB_SUCCESS : 'REQUEST_JOB_SUCCESS',
    REQUEST_JOB_FAILURE : 'REQUEST_JOB_FAILURE',
}
