export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    GET_CURRENTINFO_SUCCESS: 'USERS_GET_CURRENTINFO_SUCCESS',
    GET_CURRENTINFO_FAILURE: 'USERS_GET_CURRENTINFO_FAILURE',

    GET_EXTERNALINFO_SUCCESS: 'USERS_GET_EXTERNALINFO_SUCCESS',
    GET_EXTERNALINFO_FAILURE: 'USERS_GET_EXTERNALINFO_FAILURE',

    GET_CURRENTREVIEWS_SUCCESS: 'GET_CURRENTREVIEWS_SUCCESS',
    GET_CURRENTREVIEWS_FAILURE: 'GET_CURRENTREVIEWS_FAILURE',

    POST_REVIEW_SUCCESS: 'POST_REVIEW_SUCCESS',
    POST_REVIEW_FAILURE: 'POST_REVIEW_FAILURE',

    GET_OTHERINFO_SUCCESS: 'USERS_GET_OTHERINFO_SUCCESS',
    GET_OTHERINFO_FAILURE: 'USERS_GET_OTHERINFO_FAILURE',

    GET_ACTIVEJOBS_SUCCESS: 'USERS_GET_ACTIVEJOBS_SUCCESS',
    GET_ACTIVEJOBS_FAILURE: 'USERS_GET_ACTIVEJOBS_FAILURE',

    GET_UPCOMINGJOBS_SUCCESS: 'USERS_GET_UPCOMINGJOBS_SUCCESS',
    GET_UPCOMINGJOBS_FAILURE: 'USERS_GET_UPCOMINGJOBS_FAILURE',

    GET_RECENTJOBS_SUCCESS: 'USERS_GET_RECENTJOBS_SUCCESS',
    GET_RECENTJOBS_FAILURE: 'USERS_GET_RECENTJOBS_FAILURE',

    EDITINFO_SUCCESS: 'USERS_EDITINFO_SUCCESS',
    EDITINFO_FAILURE: 'USERS_EDITINFO_FAILURE',

    ADDPET_SUCCESS: 'ADDPET_SUCCESS',
    ADDPET_FAILURE: 'ADDPET_FAILURE',

    ACCEPT_JOB_SITTER_SUCCESS: 'ACCEPT_JOB_SITTER_SUCCESS',
    ACCEPT_JOB_SITTER_FAILURE: 'ACCEPT_JOB_SITTER_FAILURE',

    EDITPET_SUCCESS: 'EDITPET_SUCCESS',
    EDITPET_FAILURE: 'EDITPET_FAILURE',

    DELETEPET_SUCCESS: 'DELETEPET_SUCCESS',
    DELETEPET_FAILURE: 'DELETEPET_FAILURE',
};

